FROM centos:7

LABEL maintainer="yee.yi@vesoft.com"

RUN yum update -y \
  && yum install -y centos-release-scl \
  && yum install -y devtoolset-8 \
  && yum install -y \
    autoconf \
    autoconf-archive \
    automake \
    file \
    git \
    java-1.8.0-openjdk \
    libtool \
    libstdc++-static \
    make \
    maven \
    ncurses-devel \
    perl \
    perl-WWW-Curl \
    readline-devel \
    unzip \
    vim \
    wget \
    xz-devel \
  && yum clean all \
  && rm -rf /var/cache/yum

RUN scl enable devtoolset-8 -- bash \
  && mkdir -p /home/nebula \
  && ln -snf /opt/rh/devtoolset-8/enable /etc/profile.d/devtoolset-8.sh

ENV DEVTOOLSET_PATH /opt/rh/devtoolset-8/root
ENV NEBULA_HOME /home/nebula
ENV EXTRA_CXXFLAGS "-O2 -m64 -march=x86-64"
ENV EXTRA_PIC_CXXFLAGS "${EXTRA_CXXFLAGS} -fPIC -DPIC"
ENV EXTRA_LDFLAGS "-static-libgcc -static-libstdc++"

WORKDIR ${NEBULA_HOME}

# Install cmake-3.11.4 before openssl
RUN wget https://github.com/Kitware/CMake/releases/download/v3.11.4/cmake-3.11.4.tar.gz \
  && tar zxf cmake-3.11.4.tar.gz \
  && cd cmake-3.11.4 \
  && . /etc/profile.d/devtoolset-8.sh \
  && CXXFLAGS=${EXTRA_PIC_CXXFLAGS} CFLAGS=$CXXFLAGS CPPFLAGS=$CXXFLAGS LDFLAGS=${EXTRA_LDFLAGS} ./configure --prefix=${DEVTOOLSET_PATH}/usr && make && make install \
  && cd .. \
  && rm -rf cmake-*

# Install openssl-1.1.1c
RUN wget https://www.openssl.org/source/openssl-1.1.1c.tar.gz \
  && tar zxf openssl-1.1.1c.tar.gz \
  && cd openssl-1.1.1c \
  && . /etc/profile.d/devtoolset-8.sh \
  && ./config --prefix=${DEVTOOLSET_PATH}/usr --openssldir=${DEVTOOLSET_PATH}/usr no-shared threads ${EXTRA_CXXFLAGS} ${EXTRA_LDFLAGS} \
  && make && make install \
  && cd .. \
  && rm -rf openssl-*

# Install bison-3.0.5
RUN wget http://ftp.gnu.org/gnu/bison/bison-3.0.5.tar.gz \
  && tar xf bison-3.0.5.tar.gz \
  && cd bison-3.0.5 \
  && . /etc/profile.d/devtoolset-8.sh \
  && CXXFLAGS="${EXTRA_PIC_CXXFLAGS}" CFLAGS=$CXXFLAGS CPPFLAGS=$CXXFLAGS LDFLAGS="${EXTRA_LDFLAGS}" ./configure --prefix=${DEVTOOLSET_PATH}/usr --enable-shared=no --enable-static \
  && make && make install \
  && cd .. \
  && rm -rf bison-*

# Install flex-2.6.4
RUN wget https://github.com/westes/flex/releases/download/v2.6.4/flex-2.6.4.tar.gz \
  && tar zxf flex-2.6.4.tar.gz \
  && cd flex-2.6.4 \
  && . /etc/profile.d/devtoolset-8.sh \
  && CXXFLAGS=${EXTRA_PIC_CXXFLAGS} CFLAGS=$CXXFLAGS CPPFLAGS=$CXXFLAGS LDFLAGS=${EXTRA_LDFLAGS} ./configure --prefix=${DEVTOOLSET_PATH}/usr --enable-shared=no \
  && make && make install \
  && cd .. \
  && rm -rf flex-*

# Install boost-1.66
RUN wget https://dl.bintray.com/boostorg/release/1.66.0/source/boost_1_66_0.tar.gz \
  && tar zxf boost_1_66_0.tar.gz \
  && cd boost_1_66_0 \
  && . /etc/profile.d/devtoolset-8.sh \
  && ./bootstrap.sh --prefix=${DEVTOOLSET_PATH}/usr --without-icu --without-libraries=python \
  && ./b2 cxxflags=${EXTRA_CXXFLAGS} linkflags="" link=static runtime-link=static install \
  && ./b2 --clean-all \
  && cd .. \
  && rm -rf boost_*

# Install gperf-3.1
RUN wget http://ftp.gnu.org/pub/gnu/gperf/gperf-3.1.tar.gz \
  && tar zxf gperf-3.1.tar.gz \
  && cd gperf-3.1 \
  && . /etc/profile.d/devtoolset-8.sh \
  && CXXFLAGS=${EXTRA_PIC_CXXFLAGS} CFLAGS=$CXXFLAGS CPPFLAGS=$CXXFLAGS LDFLAGS=${EXTRA_LDFLAGS} ./configure --prefix=${DEVTOOLSET_PATH}/usr --enable-shared=no \
  && make && make install \
  && cd .. \
  && rm -rf gperf-*

# Install krb5-1.16.3
RUN wget https://github.com/krb5/krb5/archive/krb5-1.16.3-final.tar.gz \
  && tar zxf krb5-1.16.3-final.tar.gz \
  && cd krb5-krb5-1.16.3-final/src \
  && . /etc/profile.d/devtoolset-8.sh \
  && autoreconf \
  && CXXFLAGS=$EXTRA_PIC_CXXFLAGS CFLAGS=$CXXFLAGS CPPFLAGS=$CXXFLAGS LDFLAGS=${EXTRA_LDFLAGS} ./configure --prefix=${DEVTOOLSET_PATH}/usr --enable-static --disable-shared --disable-rpath --disable-aesni --disable-thread-support \
  && make all && make install \
  && cd .. \
  && rm -rf krb5-*

# Install libunwind-1.2.1
RUN wget https://github.com/libunwind/libunwind/releases/download/v1.2.1/libunwind-1.2.1.tar.gz \
  && tar zxf libunwind-1.2.1.tar.gz \
  && cd libunwind-1.2.1 \
  && . /etc/profile.d/devtoolset-8.sh \
  && CXXFLAGS=${EXTRA_PIC_CXXFLAGS} CFLAGS=$CXXFLAGS CPPFLAGS=$CXXFLAGS LDFLAGS=${EXTRA_LDFLAGS} ./configure --prefix=${DEVTOOLSET_PATH}/usr --enable-shared=no \
  && cd .. \
  && rm -rf libunwind-*

# Build and Install thirdparty
RUN git clone --single-branch --branch master https://github.com/vesoft-inc/nebula-3rdparty.git ${NEBULA_HOME}/nebula-3rdparty \
  && cd ${NEBULA_HOME}/nebula-3rdparty \
  && . /etc/profile.d/devtoolset-8.sh \
  && cmake -DSKIP_JAVA_JAR=ON . \
  && make && make install \
  && cd ${NEBULA_HOME} \
  && rm -rf ${NEBULA_HOME}/*
